In [ ]:
import pandas as pd

df = pd.read_json(r"outputs\output4.jsonl", lines=True,encoding="utf-16")

In [28]:
# sorts the user_id, time, and location_ids
df.sort_values(["user_id", "timestamp", "location_id"], inplace=True)
df[df["user_id"] == "USER_411f5a7e4a1d4075a1572edc5e9684b7"]

,timestamp,user_id,room_id,building_id,location_id,success
4965,2025-10-19 07:55:37.609000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_a5c8344ce9224b51bcff642a28e89871,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
5119,2025-10-19 07:57:47.451000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_fb5aa25276314dea867a71881803c85d,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
48772,2025-10-19 10:59:58.686000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_a5c8344ce9224b51bcff642a28e89871,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
48773,2025-10-19 10:59:59.025000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_211b5fa8b7ac4beea91d576226e8733d,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
70718,2025-10-19 12:26:15.294000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_a5c8344ce9224b51bcff642a28e89871,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
70721,2025-10-19 12:26:15.472000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_226653e41f2744878b504b0f6093e703,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
96446,2025-10-19 14:22:54.071000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_a5c8344ce9224b51bcff642a28e89871,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
96450,2025-10-19 14:22:54.258000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_fb5aa25276314dea867a71881803c85d,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
106758,2025-10-19 15:08:45.155000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_a5c8344ce9224b51bcff642a28e89871,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
106890,2025-10-19 15:09:13.181000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_5cfd408adff4418cbdd8f6df7ba9845a,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
127543,2025-10-19 16:11:43.823000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_a5c8344ce9224b51bcff642a28e89871,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
127544,2025-10-19 16:11:43.851000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_211b5fa8b7ac4beea91d576226e8733d,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
138591,2025-10-19 16:47:53.952000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_a5c8344ce9224b51bcff642a28e89871,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True
138593,2025-10-19 16:47:54.081000+00:00,USER_411f5a7e4a1d4075a1572edc5e9684b7,ROOM_cd30dc272cfb4fda8d4ab013b86c6041,BLD_48eb0748769645df9c1b0cee60c00aa7,LOC_100a15b3ee89401aa7800cdef1c05289,True

In [29]:
# sorts the user_id, time, and location_ids
df.sort_values(["user_id", "timestamp", "location_id"], inplace=True)
#df
df[df["user_id"] == "USER_72f06f7bd18142c9935593c089195c0f"]

,timestamp,user_id,room_id,building_id,location_id,success
18477,2025-10-19 08:37:55.047000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_af3a5b86858e49ac8ca1db3e36a555a0,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
18478,2025-10-19 08:37:55.248000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_3041c08fae9c4e578b2e8259b6e2b5cc,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
28701,2025-10-19 09:33:33.389000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_af3a5b86858e49ac8ca1db3e36a555a0,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
28703,2025-10-19 09:33:33.591000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_93a95c4bb94a43d1ad1d28f50c7d50d3,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
31883,2025-10-19 09:52:01.204000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_a42411dff02a4084bcb2a46140df12e5,BLD_6e4a113eaae946029a4f0f0270a3c263,LOC_2f3178401a6d4116970750f0e2b15027,False
73220,2025-10-19 12:35:14.757000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_af3a5b86858e49ac8ca1db3e36a555a0,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
74027,2025-10-19 12:38:15.430000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_00c0ce0c35bc4533a64c419e94e0a364,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
74100,2025-10-19 12:38:29.639000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_b04cf59f84ba4aa7af47b9183e6278fb,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,False
100922,2025-10-19 14:45:29.994000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_af3a5b86858e49ac8ca1db3e36a555a0,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
101263,2025-10-19 14:47:26.186000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_c4f3594b6db641aba8733a6c6be4af25,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
102224,2025-10-19 14:53:00.842000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_7342ca5eac894e778e2a2bc187c05c50,BLD_6e4a113eaae946029a4f0f0270a3c263,LOC_2f3178401a6d4116970750f0e2b15027,False
133175,2025-10-19 16:30:03.394000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_af3a5b86858e49ac8ca1db3e36a555a0,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
133938,2025-10-19 16:32:19.853000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_93a95c4bb94a43d1ad1d28f50c7d50d3,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
135550,2025-10-19 16:37:17.080000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_af3a5b86858e49ac8ca1db3e36a555a0,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
136054,2025-10-19 16:38:59.770000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_c4f3594b6db641aba8733a6c6be4af25,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
153261,2025-10-19 17:53:05.040000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_af3a5b86858e49ac8ca1db3e36a555a0,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
153813,2025-10-19 17:56:24.478000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_3041c08fae9c4e578b2e8259b6e2b5cc,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
153814,2025-10-19 17:56:24.718000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_83d9bbbb666f4a5e908b0c7205eb1e36,BLD_6e4a113eaae946029a4f0f0270a3c263,LOC_2f3178401a6d4116970750f0e2b15027,False
155777,2025-10-19 18:10:06.675000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_af3a5b86858e49ac8ca1db3e36a555a0,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
155778,2025-10-19 18:10:06.865000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_e1026968d57945719f118cb65e37d5e7,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
159837,2025-10-19 20:05:44.476000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_af3a5b86858e49ac8ca1db3e36a555a0,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
159846,2025-10-19 20:06:55.369000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_98d116c949f94ea88e815b80dbf48a4b,BLD_46a22c25b09046f2913cfe35f9a9df75,LOC_2f3178401a6d4116970750f0e2b15027,True
159906,2025-10-19 20:17:28.754000+00:00,USER_72f06f7bd18142c9935593c089195c0f,ROOM_72324eb7f4544b7485d947721f913c7d,BLD_bfd20a50b57e4505aa36e7a8e131817c,LOC_2f3178401a6d4116970750f0e2b15027,False

In [30]:
# old system
# gets the difference between the first and second unique loc
def diff_between_unique_place(group, place):
    #saves the first min and min location
    firstMin = group["timestamp"].min()
    firstLoc = group.loc[group["timestamp"].idxmin(), place]

    # filters out same location 
    filteredGroup = group[group[place] != firstLoc] 

    # finds second min
    secondMin = filteredGroup["timestamp"].min()

    return secondMin - firstMin

In [31]:
# place has to be building_id, room_id, or location_id
def smallest_diff_between_unique_place(group, place):

    diffBetweenUniquePlace = []

    sortedValues = group.sort_values(by="timestamp").reset_index(drop=True)

    for i in range(len(sortedValues) - 1):
        # if location is the same go next because its not unique location
        if sortedValues.loc[i, place] == sortedValues.loc[i+1, place]:
            continue

        # get the difference between loc
        diff = sortedValues.loc[i+1, "timestamp"] - sortedValues.loc[i, "timestamp"]

        diffBetweenUniquePlace.append(diff)

    if not diffBetweenUniquePlace:
        return "NaT"
    else:
        return min(diffBetweenUniquePlace)

In [32]:
# groups by the user so its all the unique users and it applys the difference_between_unique_loc function
locDiff = df.groupby("user_id").apply(lambda group: smallest_diff_between_unique_place(group, "location_id"), include_groups=False)

locFilterNaT = locDiff[locDiff != "NaT"]
# get users if travel times between 2 location is less than 4 hours 
filterLoc = locFilterNaT[locFilterNaT < pd.Timedelta("4h")]

clonedUserBadges= filterLoc.reset_index()["user_id"]

clonedUserBadges

0     USER_206dc89bba5e494a9d3d8c54b801f8c2
1     USER_39e3f7d52b344c5db490c9a1dca8e55c
2     USER_3ad100ba94134bdda6fd632a35ef5bbf
3     USER_574cbd1d690e4dc2b03415986f12953e
4     USER_5d6519136e524a4387ff82ee6192e7e5
5     USER_70d6755321d44b2981b7ae0604bf1be7
6     USER_904b9ec87bcf4b16a652ddba4ed83477
7     USER_aa33870e58ca4ce6ade5f29403dda07d
8     USER_c43382b2fd8c40f9916870b589cc68a2
9     USER_ca11eec10b01453e817a627816372372
10    USER_f1e0189b7426459b9421934401312437
11    USER_f8088c4c026546d4a7d623d8f2ebdef5
Name: user_id, dtype: object

In [33]:
# groups the users and does the same thing on the top
roomDiff = df.groupby("user_id").apply(lambda group: smallest_diff_between_unique_place(group, "room_id"), include_groups=False)

roomFilterNaT = roomDiff[roomDiff != "NaT"]
# filter the buildingDiff series its duplicate time
clonedUserBadges = roomFilterNaT[(roomFilterNaT < pd.Timedelta("100ms"))]
#clonedUserBadges
clonedUserDF = clonedUserBadges.to_frame().reset_index()
clonedUserDF

# get succes == False
filterByFailedEntry = df[df["success"] == False]
filterByFailedEntry

# get only unique values
curiousUsers = filterByFailedEntry["user_id"].unique()

print(f"Amount of users that have failed to access rooms that they are not authorized to access {len(curiousUsers)}")
clonedUserDF[clonedUserDF["user_id"].isin(curiousUsers)]

Amount of users that have failed to access rooms that they are not authorized to access 551

                                    user_id                      0
11    USER_00c2151b148e4f68adb316e823fe7385 0 days 00:00:00.017000
28    USER_01f89c9b0f804498b5a52dd994796151 0 days 00:00:00.026000
52    USER_03024fc802b045f29ae0867283df8824 0 days 00:00:00.055000
61    USER_03a8349680944a859a22417a577a0784 0 days 00:00:00.027000
74    USER_045b0354fa5d47c9aba74cb60e7b37be 0 days 00:00:00.046000
...                                     ...                    ...
4599  USER_f3d7edfd1de2445282b09bda22db8c06 0 days 00:00:00.037000
4601  USER_f3e40f7ac46043799ef4da3b0ab09db2 0 days 00:00:00.040000
4645  USER_f5b68ea5fb654597bb87263b6a87042a 0 days 00:00:00.028000
4677  USER_f78118a849a64964aeae33b20b477516 0 days 00:00:00.012000
4830  USER_fff5ef7db46248fc8fc3fb284d6d536b 0 days 00:00:00.035000

[290 rows x 2 columns]

In [34]:
# this notbook finds the cloned in buildings 

# groups the users and does the same thing on the top
buildingDiff = df.groupby("user_id").apply(lambda group: smallest_diff_between_unique_place(group, "building_id"), include_groups=False)

buildingFilterNaT = buildingDiff[buildingDiff != "NaT"]
# filter the buildingDiff series its duplicate time
buildingFilterNaT[(buildingFilterNaT < pd.Timedelta("1s"))]

user_id
USER_0572ee3be75545a69570cd918059ff1e    0 days 00:00:00.307000
USER_206dc89bba5e494a9d3d8c54b801f8c2    0 days 00:00:00.268000
USER_3ad100ba94134bdda6fd632a35ef5bbf    0 days 00:00:00.041000
USER_44fda9729717481cba9a9d26c597c96e    0 days 00:00:00.063000
USER_574cbd1d690e4dc2b03415986f12953e    0 days 00:00:00.052000
USER_5bcd067f2cf9417e8924740773992da7    0 days 00:00:00.398000
USER_72f06f7bd18142c9935593c089195c0f    0 days 00:00:00.240000
USER_74329a0e55a046c19458174b458281a7    0 days 00:00:00.181000
USER_8bd6fc6d02274ded9204e1301967f38a    0 days 00:00:00.133000
USER_b5cb601c7a474815b1acf4fa9e43b310    0 days 00:00:00.495000
USER_cdc1af7735ff48d2bf1e5bcff1d5d14c    0 days 00:00:00.252000
USER_d1343053c3c84816bf6c748a2159e301    0 days 00:00:00.222000
USER_d67972f5cb91411b8708d21954cb5fe1    0 days 00:00:00.312000
USER_f8088c4c026546d4a7d623d8f2ebdef5    0 days 00:00:00.149000
dtype: object