In [1]:
import pandas as pd

df = pd.read_json("output_utf8.jsonl", lines=True)

In [2]:
df.index

RangeIndex(start=0, stop=162788, step=1)

In [3]:
# index the column
(df[["user_id", "location_id"]])

,user_id,location_id
0,USER_8e8f725b85f546a996ff33038c028a49,LOC_898970f5f9424471a1bb398f8aafeecc
1,USER_67c29b8d254e48e09defa4a9d5999551,LOC_cd23590a73fd4a85afdb964c4896687a
2,USER_feb6f8b243a1430c92b19554b82faac2,LOC_4c39a3152504407688a99a05dc58c16c
3,USER_b5e4a7af754e45dd8064c3361b386787,LOC_992a413b6cc84815836fcf0c4b8862eb
4,USER_c99aebee2a76491d8811d5d2e19f3ea8,LOC_4c39a3152504407688a99a05dc58c16c
...,...,...
162783,USER_250424349ee94d76ae508563b00788f0,LOC_9768d8c47e8743c79bc94d9042921b74
162784,USER_05f3356bb9324db9b23e6a752898884f,LOC_23d72fff5124413dacef3164db84ccbf
162785,USER_3b76d8763fe649e486663ec001b148a2,LOC_23d72fff5124413dacef3164db84ccbf
162786,USER_a2bf26439ea045d1969c50402be8e1f1,LOC_3717cb8b6356495fa3b647f66d6242c0
162787,USER_86b55d92831343a9af4e6d577b141965,LOC_3717cb8b6356495fa3b647f66d6242c0

In [4]:
# index the row
# df.iloc[0]

# directly access the specific column of the row you got
df.iloc[0]["location_id"]

'LOC_898970f5f9424471a1bb398f8aafeecc'

In [5]:
# Filtering > != <
# df[df["success"] == False]
df[df["user_id"] == "USER_2239d49deaf14e01bb260367a4467920"]
# you can also multifilter
# filters only this user and if they failed trying to open a room
# you can use or (|) 
#df[(df["user_id"] == "USER_8c7ca6b20cdd40d28785eab8195f970b") & (df["success"] == False)]

,timestamp,user_id,room_id,building_id,location_id,success
3372,2025-10-14 07:30:15.707000+00:00,USER_2239d49deaf14e01bb260367a4467920,ROOM_a799a065179e458e8b13ffd2387048e8,BLD_688cc2507faa459eac60d0339eaacb5c,LOC_9768d8c47e8743c79bc94d9042921b74,True
3606,2025-10-14 07:34:22.414000+00:00,USER_2239d49deaf14e01bb260367a4467920,ROOM_c13b79f6ce4244db9a96753bab81716f,BLD_688cc2507faa459eac60d0339eaacb5c,LOC_9768d8c47e8743c79bc94d9042921b74,True
38858,2025-10-14 10:18:50.472000+00:00,USER_2239d49deaf14e01bb260367a4467920,ROOM_a799a065179e458e8b13ffd2387048e8,BLD_688cc2507faa459eac60d0339eaacb5c,LOC_9768d8c47e8743c79bc94d9042921b74,True
38952,2025-10-14 10:19:15.668000+00:00,USER_2239d49deaf14e01bb260367a4467920,ROOM_329cccd5197a41248b8569bc4f853b84,BLD_688cc2507faa459eac60d0339eaacb5c,LOC_9768d8c47e8743c79bc94d9042921b74,True
64983,2025-10-14 12:00:53.913000+00:00,USER_2239d49deaf14e01bb260367a4467920,ROOM_a799a065179e458e8b13ffd2387048e8,BLD_688cc2507faa459eac60d0339eaacb5c,LOC_9768d8c47e8743c79bc94d9042921b74,True
65035,2025-10-14 12:01:05.367000+00:00,USER_2239d49deaf14e01bb260367a4467920,ROOM_52e498a8f0f44e21875825e6ae986d9c,BLD_688cc2507faa459eac60d0339eaacb5c,LOC_9768d8c47e8743c79bc94d9042921b74,True
67154,2025-10-14 12:09:25.642000+00:00,USER_2239d49deaf14e01bb260367a4467920,ROOM_a799a065179e458e8b13ffd2387048e8,BLD_688cc2507faa459eac60d0339eaacb5c,LOC_9768d8c47e8743c79bc94d9042921b74,True
68400,2025-10-14 12:14:22.820000+00:00,USER_2239d49deaf14e01bb260367a4467920,ROOM_8efb9a178bca4bdba78fde92c660442a,BLD_688cc2507faa459eac60d0339eaacb5c,LOC_9768d8c47e8743c79bc94d9042921b74,True
101230,2025-10-14 14:41:41.420000+00:00,USER_2239d49deaf14e01bb260367a4467920,ROOM_a799a065179e458e8b13ffd2387048e8,BLD_688cc2507faa459eac60d0339eaacb5c,LOC_9768d8c47e8743c79bc94d9042921b74,True
101231,2025-10-14 14:41:41.533000+00:00,USER_2239d49deaf14e01bb260367a4467920,ROOM_c13b79f6ce4244db9a96753bab81716f,BLD_688cc2507faa459eac60d0339eaacb5c,LOC_9768d8c47e8743c79bc94d9042921b74,True

In [6]:
df["count"] = df["user_id"].map(df["user_id"].value_counts())
# least to greatest
df.sort_values("count", ascending=True, inplace=True)
print(df[["user_id", "count"]])

                                      user_id  count
121396  USER_5aeebd6a016641a39ca863fdc3e4c48c     10
154367  USER_14f33a18070545d8b3c1fd38b87f6877     10
72139   USER_24be3c96bd224d74b66168fd2c1e6831     10
121377  USER_9cf89ecfbaac4588a064dfcf628bbde4     10
23770   USER_493727be524546f6872d0710a6c9b0d8     10
...                                       ...    ...
1592    USER_8b9b2eeb900c4abcb38d25ffa94005f4     37
162332  USER_8b9b2eeb900c4abcb38d25ffa94005f4     37
1662    USER_694ae08e6e1e42b9b6528ccd0e775079     37
162419  USER_8b9b2eeb900c4abcb38d25ffa94005f4     37
161749  USER_8e8f725b85f546a996ff33038c028a49     37

[162788 rows x 2 columns]

In [7]:
diff=df.loc[0,"timestamp"] - df.loc[1633,"timestamp"]
print(df.loc[0,"timestamp"])
print(diff.total_seconds())

2025-10-14 00:00:04.108000+00:00
-21870.382